name: rescape
description: Inventory manager

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  permission_handler: ^5.1.0+2
  camera: ^0.8.0
  google_ml_kit: ^0.0.3+1
  google_fonts: ^2.0.0
  sqflite: ^2.0.0+2
  shared_preferences: ^2.0.3
  vibration: ^1.7.4-nullsafety.0
  file_picker: ^3.0.0
  pinput: ^1.1.0
  path_provider: ^2.0.1
  images_to_pdf: ^0.0.1
  decimal: ^1.0.0
  flutter_sound: ^8.0.0+6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  
  assets:
    - assets/

  fonts:
    - family: CenturyGothic
      fonts:
        - asset: assets/fonts/CenturyGothic.ttf
